export const users = [
    {userName: "omemarizvi", 
    firstName: "Omema", 
    lastName: "Rizvi", 
    school: "Habib University", 
    classLevel:"Junior", 
    email: "omemaadnan@gmail.com", 
    profilePicture: "1" },

    {userName: "amnah", 
    firstName: "Amna", 
    lastName: "Zafar", 
    school: "Dow University", 
    classLevel:"Freshman", 
    email: "amna.zafar@example.com", 
    profilePicture: "2" },

    {userName: "sonum", 
    firstName: "Sonum", 
    lastName: "Punshi", 
    school: "University of Texas Arlington", 
    classLevel:"Senior", 
    email: "sonum@example.com", 
    profilePicture: "3" },

    {userName: "nabira1", 
    firstName: "Nabira", 
    lastName: "Wahid", 
    school: "Ziauddin University", 
    classLevel:"Freshman", 
    email: "nabira.wahid@example.com", 
    profilePicture: "4" },

    {userName: "bogus5", 
    firstName: "Lena", 
    lastName: "Thompson", 
    school: "University of North Carolina at Chapel Hill", 
    classLevel:"Sophomore", 
    email: "lena.thompson@example.com", 
    profilePicture: "5" }
  ]
